namespace ValCraft
{
    // Generated by tools/armor_sets.py: Valheim armor that becomes ValCraft's Minecraft armor (added to
    // ValCraft.loot.txt, see Loot).
    public static class ValheimArmorLoot
    {
        public const string Marker = "# Valheim armor (ValCraft 0.6.3)";
        public const string Lines = Marker + @"
HelmetLeather = valcraft:leather_helmet
ArmorLeatherChest = valcraft:leather_chestplate
ArmorLeatherLegs = valcraft:leather_leggings
HelmetTrollLeather = valcraft:troll_helmet
ArmorTrollLeatherChest = valcraft:troll_chestplate
ArmorTrollLeatherLegs = valcraft:troll_leggings
HelmetBronze = valcraft:bronze_helmet
ArmorBronzeChest = valcraft:bronze_chestplate
ArmorBronzeLegs = valcraft:bronze_leggings
HelmetRoot = valcraft:root_helmet
ArmorRootChest = valcraft:root_chestplate
ArmorRootLegs = valcraft:root_leggings
HelmetIron = valcraft:iron_helmet
ArmorIronChest = valcraft:iron_chestplate
ArmorIronLegs = valcraft:iron_leggings
HelmetFenring = valcraft:fenris_helmet
ArmorFenringChest = valcraft:fenris_chestplate
ArmorFenringLegs = valcraft:fenris_leggings
HelmetDrake = valcraft:wolf_helmet
ArmorWolfChest = valcraft:wolf_chestplate
ArmorWolfLegs = valcraft:wolf_leggings
HelmetLox = valcraft:lox_helmet
ArmorLoxChest = valcraft:lox_chestplate
ArmorLoxLegs = valcraft:lox_leggings
HelmetPadded = valcraft:padded_helmet
ArmorPaddedCuirass = valcraft:padded_chestplate
ArmorPaddedGreaves = valcraft:padded_leggings
HelmetMage = valcraft:eitr_helmet
ArmorMageChest = valcraft:eitr_chestplate
ArmorMageLegs = valcraft:eitr_leggings
HelmetCarapace = valcraft:carapace_helmet
ArmorCarapaceChest = valcraft:carapace_chestplate
ArmorCarapaceLegs = valcraft:carapace_leggings
HelmetBerserkerHood = valcraft:bear_helmet
ArmorBerserkerChest = valcraft:bear_chestplate
ArmorBerserkerLegs = valcraft:bear_leggings
HelmetBerserkerUndead = valcraft:vilebone_helmet
ArmorBerserkerUndeadChest = valcraft:vilebone_chestplate
ArmorBerserkerUndeadLegs = valcraft:vilebone_leggings
HelmetAshlandsMediumHood = valcraft:ask_helmet
ArmorAshlandsMediumChest = valcraft:ask_chestplate
ArmorAshlandsMediumlegs = valcraft:ask_leggings
HelmetMage_Ashlands = valcraft:embla_helmet
ArmorMageChest_Ashlands = valcraft:embla_chestplate
ArmorMageLegs_Ashlands = valcraft:embla_leggings
HelmetFlametal = valcraft:flametal_helmet
ArmorFlametalChest = valcraft:flametal_chestplate
ArmorFlametalLegs = valcraft:flametal_leggings
HelmetDNHeavy = valcraft:protector_helmet
ArmorDeepNorthHeavyChest = valcraft:protector_chestplate
ArmorDeepNorthHeavylegs = valcraft:protector_leggings
HelmetDNMediumHood = valcraft:vanguard_helmet
ArmorDeepNorthMediumChest = valcraft:vanguard_chestplate
ArmorDeepNorthMediumlegs = valcraft:vanguard_leggings
HelmetDNMage = valcraft:caller_helmet
ArmorDeepNorthMageChest = valcraft:caller_chestplate
ArmorDeepNorthMagelegs = valcraft:caller_leggings
HelmetFishingHat = valcraft:fishing_helmet
HelmetCrownofValheim = valcraft:crown_helmet
HelmetDverger = valcraft:dverger_helmet
";
    }
}
