"""Writes mead_bases.txt: Valheim's mead bases are bowls of the same shape that differ in their
contents, so one bowl drawing (redrawn from Valheim's icons) is coloured per base from its icon.

  python tools/item_art/make_mead_bases.py
"""
import os

BOWL = [
    "................",
    "................",
    "................",
    "................",
    "....rrrrrrrr....",
    "..rrcccchcccrr..",
    ".rcckccccckcccr.",
    ".rchcckccccckcr.",
    ".rckccccchkcccr.",
    "..rrccckccccrr..",
    ".RrrrrrrrrrrrrR.",
    "..RrrrrrrrrrrR..",
    "...RRrrrrrrRR...",
    ".....RRRRRR.....",
    "................",
    "................",
]
WOOD = ("a0703c", "6a4520", "2a1a0c")
IRON = ("54545c", "32323a", "141418")

# texture, Valheim prefab, bowl, contents, contents highlight, chunks
BASES = [
    ("mead_base_anti_sting", "MeadBaseBugRepellent", WOOD, "e8b830", "f8e080", "9a78c0"),
    ("mead_base_berserkir", "MeadBaseBzerker", IRON, "8a1818", "b84040", "d03030"),
    ("mead_base_lingering_eitr", "MeadBaseEitrLingering", WOOD, "b040b0", "d878d8", "60c060"),
    ("mead_base_minor_eitr", "MeadBaseEitrMinor", WOOD, "b848b8", "e080e0", "e09040"),
    ("mead_base_frost_resistance", "MeadBaseFrostResist", WOOD, "60d8e0", "b0f4f8", "8a2a3a"),
    ("mead_base_ratatosk", "MeadBaseHasty", IRON, "4aa898", "8ad8c8", "2a4a8a"),
    ("mead_base_lingering_healing", "MeadBaseHealthLingering", IRON, "b03020", "d86050", "8a8a3a"),
    ("mead_base_major_healing", "MeadBaseHealthMajor", IRON, "c03828", "e06a50", "e0c060"),
    ("mead_base_medium_healing", "MeadBaseHealthMedium", IRON, "c82828", "e86060", "7a1010"),
    ("mead_base_minor_healing", "MeadBaseHealthMinor", IRON, "c02830", "e06068", "4060c0"),
    ("mead_base_lightfoot", "MeadBaseLightFoot", WOOD, "a088e0", "d0c0f8", "6a48b8"),
    ("mead_base_poison_resistance", "MeadBasePoisonResist", WOOD, "90a840", "c0d870", "2a6a2a"),
    ("mead_base_lingering_stamina", "MeadBaseStaminaLingering", WOOD, "f0c020", "fff080", "e07020"),
    ("mead_base_medium_stamina", "MeadBaseStaminaMedium", WOOD, "f0c830", "fff090", "e09820"),
    ("mead_base_minor_stamina", "MeadBaseStaminaMinor", WOOD, "f0c030", "fff080", "d060a0"),
    ("mead_base_troll_endurance", "MeadBaseStrength", WOOD, "a090b0", "c8b8d8", "d8b080"),
    ("mead_base_vananidir", "MeadBaseSwimmer", WOOD, "50e0b0", "a8f8e0", "e0d050"),
    ("mead_base_animal_whispers", "MeadBaseTamer", WOOD, "b0a080", "d8ccb0", "f0e4c8"),
    ("mead_base_tasty", "MeadBaseTasty", WOOD, "e8c040", "f8e490", "60a040"),
    ("barley_wine_base", "BarleyWineBase", WOOD, "e08830", "f8b860", "f8d080"),
]

out = ["# Generated by make_mead_bases.py: one bowl, coloured per mead base from Valheim's icons.", ""]
for name, prefab, bowl, c, h, k in BASES:
    out.append(f"@ {name} from={prefab} outline={bowl[2]}")
    out += [f"r {bowl[0]}", f"R {bowl[1]}", f"c {c}", f"h {h}", f"k {k}"]
    out += BOWL
    out.append("")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mead_bases.txt"), "w", encoding="utf-8").write("\n".join(out))
print(f"wrote {len(BASES)} mead bases")
