"""Turns tools/valheim_items.tsv into what the mod needs for ValCraft's Minecraft versions of Valheim
items: the table the Fabric mod registers them from, their item models, their English names, and
the loot lines (valheim/ValCraft/src/ValheimItemsLoot.cs) that turn the picked-up Valheim item into
the Minecraft one. Textures come from tools/draw_items.py; this checks each item has one.

  python tools/gen_valheim_items.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
RES = os.path.join(ROOT, "fabric", "src", "main", "resources")
ASSETS = os.path.join(RES, "assets", "valcraft")
KINDS = {"item", "mead", "weapon"}
# Valheim tools that already have a Minecraft item doing their job (BuildTools)
EXTRA_LOOT = ["Hammer = valcraft:build_hammer", "Hoe = minecraft:wooden_hoe"]
LOOT_BLOCKS = {
    "item": "# Valheim items with ValCraft versions (ValCraft 0.6.0)",
    "mead": "# Valheim items with ValCraft versions (ValCraft 0.6.0)",
    "weapon": "# Valheim weapons and tools (ValCraft 0.6.0)",
}


def rows():
    out = []
    for n, raw in enumerate(open(os.path.join(HERE, "valheim_items.tsv"), encoding="utf-8"), 1):
        line = raw.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        cells = line.split("\t")
        if len(cells) < 5:
            raise SystemExit(f"valheim_items.tsv:{n}: needs id, prefab, name, kind, stack (tab-separated)")
        item_id, prefab, name, kind, stack = (c.strip() for c in cells[:5])
        effects = cells[5].strip() if len(cells) > 5 else ""
        if kind not in KINDS:
            raise SystemExit(f"valheim_items.tsv:{n}: unknown kind {kind!r}")
        out.append((item_id, prefab, name, kind, int(stack), effects))
    ids = [r[0] for r in out]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        raise SystemExit(f"duplicate ids: {sorted(dupes)}")
    return out


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    items = rows()
    missing = [i for i, *_ in items if not os.path.exists(os.path.join(ASSETS, "textures", "item", i + ".png"))]
    if missing:
        raise SystemExit(f"no texture yet (tools/draw_items.py): {', '.join(missing)}")

    table = ["# Generated by tools/gen_valheim_items.py from tools/valheim_items.tsv: id, Valheim prefab, kind, stack, effects"]
    for item_id, prefab, _, kind, stack, effects in items:
        table.append("\t".join((item_id, prefab, kind, str(stack), effects)))
    write(os.path.join(RES, "valcraft", "valheim_items.tsv"), "\n".join(table) + "\n")

    for item_id, _, _, kind, *_ in items:
        # weapons and tools are held like Minecraft's (diagonal, in the fist)
        parent = "minecraft:item/handheld" if kind == "weapon" else "minecraft:item/generated"
        write(os.path.join(ASSETS, "items", item_id + ".json"),
              json.dumps({"model": {"type": "minecraft:model", "model": f"valcraft:item/{item_id}"}}, indent=2) + "\n")
        write(os.path.join(ASSETS, "models", "item", item_id + ".json"),
              json.dumps({"parent": parent, "textures": {"layer0": f"valcraft:item/{item_id}"}}, indent=2) + "\n")

    lang_path = os.path.join(ASSETS, "lang", "en_us.json")
    lang = json.load(open(lang_path, encoding="utf-8"))
    for item_id, _, name, *_ in items:
        lang[f"item.valcraft.{item_id}"] = name
    write(lang_path, json.dumps(lang, indent=2, ensure_ascii=False) + "\n")

    # One block of loot lines per kind of item: a loot table that has a block already gets only
    # the blocks it's missing (Loot.Load), so each set added later needs its own.
    blocks = {}
    for item_id, prefab, _, kind, *_ in items:
        blocks.setdefault(LOOT_BLOCKS[kind], []).append(f"{prefab} = valcraft:{item_id}")
    blocks[LOOT_BLOCKS["weapon"]] += EXTRA_LOOT
    entries = ",\n".join(f'            ("{marker}", @"\n{chr(10).join(lines)}\n")' for marker, lines in blocks.items())
    cs = f"""namespace ValCraft
{{
    // Generated by tools/gen_valheim_items.py from tools/valheim_items.tsv: Valheim items that become
    // ValCraft's own Minecraft versions of them when picked up (added to ValCraft.loot.txt, see Loot).
    public static class ValheimItemsLoot
    {{
        public static readonly (string marker, string lines)[] Blocks =
        {{
{entries}
        }};
    }}
}}
"""
    write(os.path.join(ROOT, "valheim", "ValCraft", "src", "ValheimItemsLoot.cs"), cs)
    print(f"{len(items)} items: table, models, names and loot lines written")


if __name__ == "__main__":
    main()
